### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by thisishugo** [kandanapp/kandan#429]
http://kandanapp.com is currently unavailable.

**Comment by scouttyg** [comment]
Trying to get this fixed but I don't control the domain, @fusion94 can we get this up?

**Comment by XVilka** [comment]
Are there any updates on this?

**Comment by jrgifford** [comment]
None here. Scott?

Suggestions for a new domain to use?

-- 
- James

**Comment by thisishugo** [comment]
getkandan.com is available

**Comment by scouttyg** [comment]
kandan.io is available too, that might be a couple good ones to get.

Its unfortunate though, because we lose all that good SEO from the other domains.

**Comment by zwarmapapa** [comment]
Ehm... They are all offline?

**Comment by scouttyg** [comment]
I bought both, kandan.io now works, still working on setting up getkandan.com. Should have this done this weekend.

**Comment by scouttyg** [comment]
Because github pages doesn't support multiple domains, hooked up getkandan.com to redirect to kandan.io. I'm not attached to one domain vs the other, so I can always switch it around if necessary.

I'll still need to modify the copy in this repo and the github page though, to reflect these new domains.

**Comment by scouttyg** [comment]
We've moved domains! We can now be found at getkandan.com or kandan.io.
